-- UGPHONE MOD: Supabase shared database
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 12),
  avatar text default '',
  role text not null default 'user' check (role in ('user','admin','free_fire','free_fire_max')),
  last_ip text default '',
  banned boolean not null default false,
  created_at timestamptz not null default now()
);
-- Username length: 3-12 characters (matches the web UI).
alter table if exists public.profiles drop constraint if exists profiles_username_length_check;
alter table if exists public.profiles add constraint profiles_username_length_check
  check (char_length(username) between 3 and 12);

create table if not exists public.keys (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  date date not null,
  limit integer not null default 1 check (limit > 0),
  used integer not null default 0 check (used >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create table if not exists public.key_claims (
  id uuid primary key default gen_random_uuid(),
  key_id uuid not null references public.keys(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  claim_date date not null,
  created_at timestamptz not null default now(),
  unique(user_id, claim_date)
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  username text not null,
  avatar text default '',
  message text not null default '' check (char_length(message) between 0 and 500),
  image_url text default '',
  created_at timestamptz not null default now()
);
create table if not exists public.server_state (
  id integer primary key default 1 check (id=1),
  status text not null default 'normal' check (status in ('normal','maintenance','resetting','resting')),
  display text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.server_state(id,status,display) values (1,'normal','') on conflict (id) do nothing;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and banned=false);
$$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,username) values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)));
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.claim_daily_key() returns text language plpgsql security definer set search_path=public as $$
declare d date; k public.keys; p public.profiles; c int;
begin
 if auth.uid() is null then raise exception 'Bạn cần đăng nhập.'; end if;
 select * into p from public.profiles where id=auth.uid();
 if p.banned then raise exception 'Tài khoản đã bị BAN.'; end if;
 select status into c from public.server_state where id=1; if c is distinct from 'normal' then raise exception 'Server đang tạm đóng.'; end if;
 d:=timezone('Asia/Ho_Chi_Minh',now())::date;
 if exists(select 1 from public.key_claims where user_id=auth.uid() and claim_date=d) then raise exception 'Bạn đã nhận KEY hôm nay.'; end if;
 select * into k from public.keys where date=d and active=true and used < limit order by created_at asc for update skip locked limit 1;
 if not found then raise exception 'Hôm nay chưa có KEY hoặc KEY đã hết lượt.'; end if;
 insert into public.key_claims(key_id,user_id,claim_date) values(k.id,auth.uid(),d);
 update public.keys set used=used+1 where id=k.id;
 return k.key;
end; $$;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user','admin','free_fire','free_fire_max'));

alter table public.profiles enable row level security;
alter table public.keys enable row level security;
alter table public.key_claims enable row level security;
alter table public.messages enable row level security;
alter table public.server_state enable row level security;

drop policy if exists profiles_select on public.profiles; create policy profiles_select on public.profiles for select using (auth.uid() is not null and (id=auth.uid() or public.is_admin()));
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update
using (id=auth.uid() or public.is_admin())
with check (id=auth.uid() or public.is_admin());

-- Prevent normal users from changing their own role/banned flag.
create or replace function public.protect_profile_privileges() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is not null and not public.is_admin() then
    if new.role is distinct from old.role or new.banned is distinct from old.banned then
      raise exception 'Không có quyền thay đổi role hoặc trạng thái BAN.';
    end if;
  end if;
  return new;
end; $$;
drop trigger if exists protect_profile_privileges on public.profiles;
create trigger protect_profile_privileges
before update on public.profiles
for each row execute procedure public.protect_profile_privileges();
drop policy if exists keys_select on public.keys; create policy keys_select on public.keys for select using (auth.uid() is not null);
drop policy if exists keys_admin_insert on public.keys; create policy keys_admin_insert on public.keys for insert with check (public.is_admin());
drop policy if exists keys_admin_update on public.keys; create policy keys_admin_update on public.keys for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists claims_self on public.key_claims; create policy claims_self on public.key_claims for select using (user_id=auth.uid() or public.is_admin());
drop policy if exists messages_select on public.messages; create policy messages_select on public.messages for select using (auth.uid() is not null);
drop policy if exists messages_insert on public.messages; create policy messages_insert on public.messages for insert with check (auth.uid()=user_id and (user_id=auth.uid() or public.is_admin()));
drop policy if exists server_select on public.server_state; create policy server_select on public.server_state for select using (auth.uid() is not null);
drop policy if exists server_admin_update on public.server_state; create policy server_admin_update on public.server_state for update using (public.is_admin()) with check (public.is_admin());

-- Enable realtime for shared UI updates.
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.keys;
alter publication supabase_realtime add table public.server_state;

-- UGPHONE MOD setup values supplied for this deployment.
-- Admin email is used by the web UI; the actual password remains in Supabase Auth.
-- Grant the admin role after the auth user exists:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='namn63657@gmail.com');

-- Seed the supplied daily KEY for 2026-10-03. Change the date/limit if this deployment uses another schedule.
insert into public.keys(key,date,limit,active)
values ('6677028@','2026-10-03',999999,true)
on conflict (key) do nothing;

-- Free Fire / Free Fire Max are application roles; they do not grant admin permissions.
-- After creating your admin account, run:
-- update public.profiles set role='admin' where username='YOUR_ADMIN_USERNAME';


-- IP bans used by server.js (never expose service_role key to the browser).
create table if not exists public.banned_ips (
  id uuid primary key default gen_random_uuid(),
  ip text not null unique,
  created_at timestamptz not null default now()
);

alter table public.banned_ips enable row level security;
drop policy if exists banned_ips_admin_all on public.banned_ips;
create policy banned_ips_admin_all on public.banned_ips for all using (public.is_admin()) with check (public.is_admin());

-- Admin product/menu posts
create table if not exists public.admin_posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  tag text,
  link text,
  image_url text,
  button_text text default '👑 LẤY FREE (9999)',
  hot boolean not null default false,
  active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.admin_posts enable row level security;
create policy "posts_public_read" on public.admin_posts for select using (active = true or public.is_admin(auth.uid()));
create policy "posts_admin_insert" on public.admin_posts for insert with check (public.is_admin(auth.uid()));
create policy "posts_admin_update" on public.admin_posts for update using (public.is_admin(auth.uid())) with check (public.is_admin(auth.uid()));
create policy "posts_admin_delete" on public.admin_posts for delete using (public.is_admin(auth.uid()));

insert into storage.buckets (id,name,public) values ('post-images','post-images',true) on conflict (id) do update set public=true;
create policy "post_images_public_read" on storage.objects for select using (bucket_id='post-images');
create policy "post_images_admin_insert" on storage.objects for insert with check (bucket_id='post-images' and public.is_admin(auth.uid()));
create policy "post_images_admin_update" on storage.objects for update using (bucket_id='post-images' and public.is_admin(auth.uid()));
create policy "post_images_admin_delete" on storage.objects for delete using (bucket_id='post-images' and public.is_admin(auth.uid()));
